Style/FormatString:
    EnforcedStyle: percent
Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma
Metrics/BlockLength:
    Exclude:
        - 'Rakefile'
        - '**/*.rake'
        - 'spec/**/*.rb'
