Generation Comics
=================

This is a tool to generate daily feeds automatically.  It's designed for
handling web comics, but it can handle any daily feed.

== Configuration

Configuration is handled by creating a `config.json` file in the main directory.
An example configuration file can be found in the `doc/example` directory.

The `link` field for a comic can accept any pattern which works with
`strftime(3)`.  The `time` field expresses a time in GMT.

You will generally want to change the `id` field in the `config` section to the
URL of your installation.  This allows the feeds to generate unique IDs that
won't conflict with other installations.

Due to the power of Ruby's in-order hash handling, comics should be listed in
the same order as they're listed in the configuration file.

== FAQ

Why did you write this tool?::
	I got tired of the link in the Dilbert feed being broken.

What formats does it generate?::
	Atom 1.0 and RSS 1.0.  Atom is recommended.

Why do you generate XHTML?::
	Atom and RSS are XML formats.  Generating XML avoids the need for encoding
	HTML and simplifies the templates significantly.

== License

Generation Comics is licensed under the MIT License.  See the `LICENSE` file for
more details.
